import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Navbar from '../../components/Navbar'
import Hero from '../../components/Hero'
import FeaturedProduct from '../../components/FeaturedProduct'
import Footer from '../../components/Footer'
import Categories from '../../components/Categories'
import axios from 'axios'
const inter = Inter({ subsets: ['latin'] })

export default function Home({ featuredProducts }) {
  return (
    
    <>
      <Head>
        <title>E-commerce</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale-1"/>
        <Link rel="icon" href="/favicon.ico"/> 
      </Head>
      <>
        <Navbar />
        <Hero />
        <Categories />
        <FeaturedProduct products={featuredProducts} />
        <Footer />
      </>
      </>
  )
}


export async function getServerSide(){
  const {data} = await axios.get(`http://localhost:3000/api/products`)

  return {
    props: {
      featuredProducts: data
    }
  }
}